### ISSUE TITLE
NPE on latest HuskyCrates

### ISSUE THREAD

**Issue by Rubbertjuh** [codeHusky/HuskyCrates-Plugin#40]
https://hastebin.com/vefobazemo.vbs is spammed quite often, this started happening as soon as we switched to the latest version of HuskyCrates. 
Running SpongeForge 1.10.2-2281-5.2.0-BETA-2379

**Comment by seshormerow** [comment]
Going to need your config as well but I have a good feeling what's causing this that's wrong in your config.

**Comment by codeHusky** [comment]
Since no additional info has been posted, this issue will be closed until a config and verification that the user is running v1.5.0 is shown.
